/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package intopark.shops;

/**
 *
 * @author arska
 */
public enum BasicBuildables {
    /* FOOD SHOPS */
    MEATBALLS,ENERGY,CAFE,NAKK_KIOSK,CANDY_STREET,POPCORNVAN,
    TRACHFOOD,SODAMACHINE,MILKSHJAKE,CHICKEM,SWEETFRUITS,WRAP_PLACE,
    INTOS_ICECREAM,PASTRY_SHOP,NORMAI_FOOD,SWEETCORN,CHIPS_N_CHICKEN,
    /* OTHER SHOPS */
    TOILET,BALLOON_STAND,CANTHROW,INFOBOARD,NEWS_STAND,JOKE_VEND,
    INFO_KIOSK,FAST_JOY,PICK_ROPE,CAMERA_STAND,RECORD_STORE,
    /* RIDES TODO: */
    CHESSCENTER,PIRATESHIP,BLENDER,ROTOR,SPINWHEEL,ARCHERYRANGE,HAUNTEDHOUSE,NULL;
}
